apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jm-master-old
  labels:
    app: jm-master-old
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jm-master-old
  template:
    metadata:
      labels:
        app: jm-master-old
    spec:
      volumes:
      - name: jmeter-pv-storage
        persistentVolumeClaim:
          claimName: jmeter-pv-claim
      containers:
      - name: jm-master
        image: dddldlw/tesi:jmeter-master-v1.0
        ports:
        - containerPort: 60000
          name: jmeter
        - containerPort: 2379
          name: etcd1
        - containerPort: 2380
          name: etcd2
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: "/mnt/"
          name: jmeter-pv-storage
       # command: ["/bin/bash"]
      #  command: ["alias jmeter='/run/jmeter_to_all_slaves.sh'"]
      imagePullSecrets:
      - name: regsecret
