kind: PersistentVolume
apiVersion: v1
metadata:
  name: jmeter-pv-storage
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jmeter-volume"