apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jm-master
  labels:
    app: jm-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jm-master
  template:
    metadata:
      labels:
        app: jm-master
    spec:
      volumes:
      - name: jmeter-pv-storage
        persistentVolumeClaim:
          claimName: jmeter-pv-claim
      containers:
      - name: jm-master
        image: tesijmeterkubernetes/jmeter:master
        ports:
        - containerPort: 60000
          name: jmeter
        - containerPort: 2379
          name: etcd1
        - containerPort: 2380
          name: etcd2
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: "/mnt/"
          name: jmeter-pv-storage
