kind: PersistentVolume
apiVersion: v1
metadata:
  name: jmeter-testcase-pv-storage
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/jmeter-testcase"
